# Generated by Django 5.2.17 on 2026-09-28 09:39

import booking.models
import datetime
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'company_holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', booking.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_events',
            },
        ),
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('opens_at', models.TimeField(default=datetime.time(9, 0))),
                ('closes_at', models.TimeField(default=datetime.time(17, 0))),
                ('minimum_minutes', models.PositiveSmallIntegerField(default=30)),
                ('maximum_minutes', models.PositiveSmallIntegerField(default=120)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=15)),
                ('gap_minutes', models.PositiveSmallIntegerField(default=15)),
                ('advance_days', models.PositiveSmallIntegerField(default=14)),
                ('check_in_minutes', models.PositiveSmallIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_policy',
            },
        ),
        migrations.CreateModel(
            name='BookingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_series', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_series',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('booking', 'Booking'), ('block', 'Room closure')], max_length=7)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('blocked', 'Blocked'), ('block_cancelled', 'Closure cancelled')], max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('occupied_from', models.DateTimeField()),
                ('occupied_until', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=8)),
                ('guest_company_name', models.CharField(blank=True, max_length=200)),
                ('external_attendee_count', models.PositiveSmallIntegerField(default=0)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('refreshments_requested', models.BooleanField(default=False)),
                ('front_desk_notes', models.TextField(blank=True)),
                ('block_reason', models.CharField(blank=True, max_length=240)),
                ('override_reason', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organized_reservations', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='booking.bookingseries')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.reservation')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('check_in', 'Check-in')], max_length=10)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.reservation')),
            ],
            options={
                'db_table': 'email_tokens',
            },
        ),
        migrations.CreateModel(
            name='BookingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='booking.reservation')),
            ],
            options={
                'db_table': 'booking_attendees',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('floor', models.CharField(max_length=40)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['location', 'floor', 'name'],
                'constraints': [models.UniqueConstraint(fields=('location', 'floor', 'name'), name='room_location_floor_name_unique'), models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='room_capacity_positive')],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='booking.room'),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.room'),
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='booking.room')),
            ],
            options={
                'db_table': 'room_facilities',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_email_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-created_at'], name='audit_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', '-created_at'], name='audit_actor_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='booking_policy_singleton'),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__lt', models.F('closes_at'))), name='booking_policy_hours_ordered'),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_minutes__lte', models.F('maximum_minutes'))), name='booking_policy_duration_ordered'),
        ),
        migrations.AddConstraint(
            model_name='bookingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('advance_days__gt', 0), ('slot_minutes__gt', 0)), name='booking_policy_steps_positive'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notification_due_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtoken',
            index=models.Index(fields=['purpose', 'expires_at'], name='email_token_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailtoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'login'), ('reservation__isnull', True)), models.Q(('purpose', 'check_in'), ('reservation__isnull', False)), _connector='OR'), name='email_token_purpose_target_valid'),
        ),
        migrations.AddConstraint(
            model_name='bookingattendee',
            constraint=models.UniqueConstraint(fields=('reservation', 'email'), name='reservation_attendee_unique'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'starts_at'], name='reservations_room_start_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['organizer', 'starts_at'], name='reservations_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'starts_at'], name='reservations_status_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='reservation_time_ordered'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('occupied_from__lte', models.F('starts_at')), ('occupied_until__gte', models.F('ends_at'))), name='reservation_occupied_contains_time'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'booking'), ('organizer__isnull', False), models.Q(('title', ''), _negated=True), ('status__in', ['confirmed', 'checked_in', 'completed', 'cancelled', 'no_show'])), models.Q(('kind', 'block'), ('organizer__isnull', True), models.Q(('block_reason', ''), _negated=True), ('status__in', ['blocked', 'block_cancelled'])), _connector='OR'), name='reservation_kind_status_fields_valid'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'block'), ('meeting_type', 'internal'), models.Q(('meeting_type', 'external'), models.Q(('guest_company_name', ''), _negated=True)), _connector='OR'), name='external_meeting_has_company'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('confirmed', 'checked_in', 'completed', 'blocked'))), expressions=[(booking.models.TsTzRange('occupied_from', 'occupied_until', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('room', '=')], name='reservation_room_occupied_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='bookingseries',
            constraint=models.CheckConstraint(condition=models.Q(('first_date__lte', models.F('last_date'))), name='series_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='roomfacility',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='room_facility_unique'),
        ),
    ]
