# Generated by Django 5.2.17 on 2026-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial_policy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailtoken',
            index=models.Index(fields=['purpose', 'email', '-created_at'], name='email_token_request_idx'),
        ),
    ]
