# Generated by Django 5.2.17 on 2026-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_emailtoken_email_token_request_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailtoken',
            name='email_token_purpose_target_valid',
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('check_in', 'Check-in'), ('staff', 'Staff sign-in code')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='emailtoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose__in', ['login', 'staff']), ('reservation__isnull', True)), models.Q(('purpose', 'check_in'), ('reservation__isnull', False)), _connector='OR'), name='email_token_purpose_target_valid'),
        ),
    ]
