# Generated by Django 5.2.17 on 2026-10-07 07:09

import booking.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_confirmed_bookings(apps, schema_editor):
    Reservation = apps.get_model("booking", "Reservation")
    Notification = apps.get_model("booking", "Notification")
    alias = schema_editor.connection.alias
    # Preserve previously confirmed meetings without inventing a reviewing admin.
    Reservation.objects.using(alias).filter(status="confirmed").update(status="approved")
    Notification.objects.using(alias).filter(reservation__isnull=False).update(reservation_revision=1)


def restore_confirmed_bookings(apps, schema_editor):
    Reservation = apps.get_model("booking", "Reservation")
    Notification = apps.get_model("booking", "Notification")
    alias = schema_editor.connection.alias
    # Old workers do not understand approval events or revision guards.
    Notification.objects.using(alias).filter(
        event_type__in=["request", "rejection"], status__in=["pending", "failed", "sending"]
    ).update(status="skipped", last_error="", lease_token=None, lease_expires_at=None)
    Reservation.objects.using(alias).filter(status="approved").update(status="confirmed")
    # The previous demo has no approval state: release unapproved requests on rollback.
    Reservation.objects.using(alias).filter(status__in=["pending", "rejected"]).update(
        status="cancelled", cancellation_reason="Approval workflow rolled back", cancelled_at=timezone.now()
    )


class Migration(migrations.Migration):
    # PostgreSQL DDL locks remain held until the data map and new guards commit.
    atomic = True

    dependencies = [
        ("booking", "0007_notification_leases_worker_heartbeat"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation",
            name="reservation_kind_status_fields_valid",
        ),
        migrations.RemoveConstraint(
            model_name="reservation",
            name="reservation_room_occupied_no_overlap",
        ),
        migrations.AddField(
            model_name="notification",
            name="reservation_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejected_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="reservation",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("checked_in", "Checked in"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No show"),
                    ("blocked", "Blocked"),
                    ("block_cancelled", "Closure cancelled"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(migrate_confirmed_bookings, restore_confirmed_bookings),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["created_at"],
                name="reservations_pending_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "booking"),
                        ("organizer__isnull", False),
                        models.Q(("title", ""), _negated=True),
                        (
                            "status__in",
                            [
                                "pending",
                                "approved",
                                "rejected",
                                "checked_in",
                                "completed",
                                "cancelled",
                                "no_show",
                            ],
                        ),
                    ),
                    models.Q(
                        ("kind", "block"),
                        ("organizer__isnull", True),
                        models.Q(("block_reason", ""), _negated=True),
                        ("status__in", ["blocked", "block_cancelled"]),
                    ),
                    _connector="OR",
                ),
                name="reservation_kind_status_fields_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "rejected"), _negated=True),
                    models.Q(
                        models.Q(("rejection_reason", ""), _negated=True), ("rejected_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="reservation_rejection_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "approved", "checked_in", "completed", "blocked"))
                ),
                expressions=[
                    (
                        booking.models.TsTzRange(
                            "occupied_from",
                            "occupied_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("room", "="),
                ],
                name="reservation_room_occupied_no_overlap",
            ),
        ),
    ]
